### ISSUE TITLE
why it the predict results are different from calling fasttext predict in command line?

### ISSUE THREAD

**Issue by nesciemus** [vrasneur/pyfasttext#10]

**Comment by vrasneur** [comment]
Hi @nesciemus,

pyfasttext uses the same C++ methods as the original fastText binary, so it must output the same probabilities.

Do you use the same fastText version in pyfasttext and in your original C++ binary?
If they are not the same, I know that the fastText people have slightly changed the text parsing (somewhat) recently, that may explain why the prediction results are different.

pyfasttext uses the latest fastText source code: https://github.com/facebookresearch/fastText/commit/6b74dfc3997593ec2e3c376f6510e990871acda7
So, can you compile your fasttext binary using the latest source code too?

Then, if the source codes are the same, can you upload your model and your outputs?

**Comment by yangchen1122** [comment]
Thanks for your reply.
It seems that the fasttext command line program takes the '\n' as the part of the input.
If I don't do strip() of the line, the result is the same.

**Comment by nesciemus** [comment]
Thanks for your reply.
It seems that the fasttext command line program takes the '\n' as part of the input.
If I don't do strip() of the line, the result is the same.
