### ISSUE TITLE
The Model just can not be loaded. | "RuntimeError: fastext tried to exit: 1"

### ISSUE THREAD

**Issue by adamleo** [vrasneur/pyfasttext#12]
The Model just can not be loaded.
I've tried every possible approach that I could came up with, nothing worked.
Some people discussed about it here: [#125](https://github.com/salestock/fastText.py/issues/125), but nothing helpful that I found.

```
EMBEDDINGS_MODEL_PATH = '~/fastText/result/fil9.bin'
self.word_model = FastText(EMBEDDINGS_MODEL_PATH)
File "src/pyfasttext.pyx", line 137, in pyfasttext.FastText.__cinit__ (src/pyfasttext.cpp:2249)
File "src/pyfasttext.pyx", line 466, in pyfasttext.FastText.load_model (src/pyfasttext.cpp:7906)
RuntimeError: fastext tried to exit: 1
```

Is there any advice someone can give me on this? It would be very helpful.

Thanks a lot.

**Comment by vrasneur** [comment]
The issue you are referring to (https://github.com/salestock/fastText.py/issues/125) is a specific problem with the other binding `fasText.py`.

`fastText.py` is not able to load models generated by the newest versions of FastText, because Facebook engineers have changed the model format.

My binding does not have this problem: it directly uses the FastText source code to load models instead of reimplementing all the loading/saving code.

For your specific issue, there can be multiple explanations:
* you are trying to load a model generated by an old FastText version. You can try to generate your model with the newest version of FastText.
* you are trying to load an invalid (corrupted) model.

Do you have any log messages? FastText outputs its errors on `stderr`.

Maybe you can upload your model somewhere if it is not too big.

**Comment by adamleo** [comment]
The model is trained from face book's fasttext using the `word-vector-example.sh` script. I actually tried it many times without any error msg came out so might not be an issue.

Also I used Gensim to load the model, and the model loaded successfully.

I tried finding `stderr`, nothing came up.

<img width="603" alt="screen shot 2017-09-02 at 12 45 45 pm" src="https://user-images.githubusercontent.com/9758779/29992334-b9e86020-8fdc-11e7-9d7a-7c0ec153fec4.png">

**Comment by vrasneur** [comment]
I think that you are using an old version of fastText.
I may add support for these versions in a future version of the `pyfasttext` binding.

Can you upload your model somewhere ?

`stderr` is not a file on disk, it's the "standard error stream" :-)
Do you see any messages in your terminal when you execute your commands?

**Comment by vrasneur** [comment]
Okay, I have added support for older fastText models and released a new version (0.3.0).

Can you try to install the module again  ? (with `pip install -U pyfasttext` or `pip install pyfasttext`)

**Comment by adamleo** [comment]
I just updated `pyfasttext` and tried it again, still the same error.

```
Loading word embeddings model
Model file cannot be opened for loading!
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/BI_AI/MemN2N-tableQA/demo/qa.py", line 456, in <module>
    run_web_demo(args.data_dir, args.model_file)
  File "/home/ubuntu/BI_AI/MemN2N-tableQA/demo/qa.py", line 428, in run_web_demo
    webapp.init(data_dir, model_file)
  File "demo/web/webapp.py", line 21, in init
    memn2n = MemN2N(data_dir, model_file)
  File "demo/qa.py", line 54, in __init__
    self.word_model = FastText(EMBEDDINGS_MODEL_PATH)
  File "src/pyfasttext.pyx", line 123, in pyfasttext.FastText.__cinit__ (src/pyfasttext.cpp:2050)
  File "src/pyfasttext.pyx", line 434, in pyfasttext.FastText.load_model (src/pyfasttext.cpp:7343)
RuntimeError: fastext tried to exit: 1
```

Will upload the model soon and share the link.

**Comment by vrasneur** [comment]
Have you had the time to upload your model somewhere?

**Comment by adamleo** [comment]
I just went through my instance, seems like somehow I deleted the model I was using... Sorry @vrasneur ...

But I downloaded the model from fb/fasttext, and trained using the `./word-vector-example.sh` file. During these days I deleted and downloaded & trained the model several times, and now the one I am using is exactly from the same source and trained with the same process, but pyfasttext is working fine on it now.

Anyway, thanks for the follow up, I'll close it now. 😃

**Comment by vrasneur** [comment]
No problem!

Thanks for using the module ;-)

**Comment by adamleo** [comment]
Btw, just curious, is it possible that I encountered the problem because I was using `python3.6`?

**Comment by vrasneur** [comment]
No, I don't see why using a more recent python version (with the same major version number) would have an impact on this.

But don't hesitate to open an issue if you have another error :-)

**Comment by adamleo** [comment]
Definitely. Thanks a lot!

**Comment by robertohalloran** [comment]
Hey guys, 

Just coming across this

> RuntimeError: fastext tried to exit: 1,

when trying to load pre-trained English language model from Facebook research site.

I found something interesting that may shed light on the nature of this problem. If the python script and the model.bin file are in separate directories and you specify the filepath for the model file in your script when using model.load_model(filepath): you get "RuntimeError: fastext tried to exit: 1". 

However, if the script and model.bin are in the same directory you can load model.bin via model.load_model(model.bin) with no problems.

Not sure what the status of this issue. I see it's been closed but I figure this is worth noting.
