### ISSUE TITLE
Can't cancel learning

### ISSUE THREAD

**Issue by RichardSieg** [vrasneur/pyfasttext#14]
Hi,
unfortunately, it's not possible to stop an already started computation. Is this something that can be fixed?
Best,
Richard

**Comment by vrasneur** [comment]
Hi Richard,

How would you like to interrupt an ongoing training?
By sending a Ctrl-C and getting a KeyboardInterrupt exception?

The original fastText source code is not engineered to allow that.
But maybe there is a way to add a flag somewhere to know if the current training should abort now... (e.g. you install a signal interrupt to catch a SIGINT).

Regards,

Vincent

**Comment by vrasneur** [comment]
Okay, I have modified the module. Training should be interruptible now with Ctrl-C.

Can you update the `pyfasttext` sources and check?
Here is the command to clone the repository: `git clone --recursive https://github.com/vrasneur/pyfasttext.git`

You have to install the `cysignals` module (that handles signal related stuff with C and Cython), with `pip install cysignals`

**Comment by RichardSieg** [comment]
Yes, it worked! Great, thank you!

**Comment by vrasneur** [comment]
Thanks for the feedback! I close the issue.
