### ISSUE TITLE
Build fails with macOS 10.12

### ISSUE THREAD

**Issue by MarcoNiemann** [vrasneur/pyfasttext#21]
With Python `2.7.14` the compilation fails on macOS 10.12. Requirements (`cython`, `cysignals`, `future` and `numpy`) are satisfied. Compilation fails both using `pip` and manual conversion. 

C-Compiler is:
```
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```cpp
src/fasttext_access.cpp:54:48: error: 'find' is a private member of 'fasttext::Dictionary'
ALLOW_CONST_METHOD_ACCESS(Dictionary, int32_t, find, const std::string&);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by vrasneur** [comment]
Hi @MarcoNiemann,

The only supported C++ compiler is g++.
(`pyfasttext` uses complicated template hacks to access `fastText` private members and members, which are only supported by g++).

**Comment by vrasneur** [comment]
I've added support for clang (it should support clang >= 3.6.0).

Can you update the source code and try again ?

**Comment by MarcoNiemann** [comment]
Many thanks @vrasneur. Works like a charm now. :+1: And cool that you added the `clang` support. Wasn't aware that it would only work with `g++`.

The issue can thus be closed.
