### ISSUE TITLE
pyfasttext import error

### ISSUE THREAD

**Issue by bananemure** [vrasneur/pyfasttext#23]
Hi I successfully installed pyfasttext in python 3.6 but at import I have this error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-fcc39b754fa9> in <module>()
----> 1 from pyfasttext import FastText

ImportError: /home/stephane.mbatchou/anaconda3/lib/python3.6/site-packages/pyfasttext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt6thread6_StateE

Thanks

**Comment by vrasneur** [comment]
Hi @bananemure,

I don't use Anaconda, but you can try the solution posted here:
https://github.com/salestock/fastText.py/issues/88#issuecomment-286429015

The command : `conda install libgcc`

Or maybe you can switch to another compiler using the `CC` environment variable?

**Comment by bananemure** [comment]
Hi @vrasneur ,
I found that it wasn't working with python 3.6 but worked with python 3.5 ....
I also try to use libgcc and it worked fine in python 3.6
May be you should add this step in the documentation.
Thanks for your great contribution

**Comment by vrasneur** [comment]
Okay, thanks!

I close the issue.
