### ISSUE TITLE
dumping trained model

### ISSUE THREAD

**Issue by rola93** [vrasneur/pyfasttext#30]
Hello

Is there a method to persist a trained model? I tried pickling model object but it throws _TypeError: no default __reduce__ due to non-trivial __cinit___

**Comment by vrasneur** [comment]
fastText automatically saves the model to the disk when you call the *model.train()* method.

You should have a *.bin* file (or a *.ftz* file if the model is quantized), and a *.vec file.

**Comment by rola93** [comment]
Thank you! I found it :D
