### ISSUE TITLE
Feature request: numpy.array instead of array.array

### ISSUE THREAD

**Issue by yaakov2** [vrasneur/pyfasttext#4]
In the current version, `model[word]` returns the word vector as an `array.array`.  
I need this output as a `numpy.array`:
* This allows me to add and scale vectors.
* This allows me to put these vectors directly into neural networks.

Of course here is a downside:
* `numpy` would be a new dependency.
* The api change may affect existing users.

There are several possible solutions:
1. Simply replace `array.array` by `numpy.array` -- accepting the downside as acceptable.
2. Add an additional API, e.g. `vec=model.get_numpy_vector(key)`
3. Add an optional argument `numpy` with default value `None` to the `FastText()` constructor: `model=FastText()` creates a model that uses `array.array` but `model=FastText(numpy=numpy)` creates a model that uses `numpy`.  The pyfasttext package itself would not depend on `numpy`.
4. Don't make any change to this package -- I would have to fork it for my needs.
5. Any other, better suggestion?

I am happy to provide a pull request for options (1), (2) or (3).

**Comment by vrasneur** [comment]
Hello,

I don't really need numpy support (for now), so I have added an optional method `FastText.get_numpy_vector(self, key)`, just like your option (2).

To compile with numpy support, type:
`python setup.py build`
or
`USE_NUMPY=1 python setup.py build`

To compile without numpy support, type:
`USE_NUMPY=0 python setup.py build`

**Comment by yaakov2** [comment]
Thanks a lot!
