### ISSUE TITLE
Installs fails with pip10

### ISSUE THREAD

**Issue by DomHudson** [vrasneur/pyfasttext#42]
## Summary
Install currently fails with pip >= 10. This is because [this line](https://github.com/vrasneur/pyfasttext/blob/master/setup.py#L18) uses pip's `.main` API which is no longer present in the package.

See for for more details:
https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html
https://github.com/pypa/pip/issues/5191

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5ikhpkeg/pyfasttext/setup.py", line 18, in <module>
        ret = pip.main(['install', 'cysignals'])
    AttributeError: module 'pip' has no attribute 'main'

**Comment by vrasneur** [comment]
Hello @DomHudson,

I have released a new version to fix that.

Can you retry with version 0.4.5?

Vincent

**Comment by DomHudson** [comment]
Thank you - the fix works.
