### ISSUE TITLE
installation failure on Mac OS with gcc 8.2: fatal error: 'random' file not found

### ISSUE THREAD

**Issue by chengwq613** [vrasneur/pyfasttext#44]
ERROR MESSAGES:
src/pyfasttext.cpp:648:10: fatal error: 'random' file not found
#include . ^~~~~~~~ . 1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1

Have installed gcc and LLVM...
UK-xxxx:vercheng$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.40.1)
Target: x86_64-apple-darwin17.7.0 Thread model: posix InstalledDir: /Library/Developer/CommandLineTools/usr/bin

tried this: https://github.com/vrasneur/pyfasttext/issues/24
didn't help
wondering if it's due to gcc latest version 8.2
Thanks

**Comment by mrdbourke** [comment]
I'm having this issue too. Did you manage to fix it?

**Comment by chengwq613** [comment]
no haven't I'm awaiting solutions from here...

**Comment by petrLorenc** [comment]
try
CXX=/usr/local/bin/g++-8 CC=/usr/local/bin/g++-8 pip3 install --no-cache pyfasttext

**Comment by chengwq613** [comment]
Thanks and it works!!

**Comment by anujgupta82** [comment]
Didnt work for me 

gcc --version _**gives**_
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**It fails with lot of errors. Last few lines being:**
error: 'struct cysigs_t' has no member named 'sig_on_count'
         if (unlikely(cysigs.sig_on_count <= 0))
                             ^~~~~~~~~~~~
    src/pyfasttext.cpp:841:43: note: in definition of macro 'unlikely'
       #define unlikely(x) __builtin_expect(!!(x), 0)
                                               ^
    error: command '/usr/local/bin/g++-8' failed with exit status 1

**any suggestions?**

**Comment by argideritzalpea** [comment]
@anujgupta82 Hey - did you ever figure this out? I have the same error and the above solutions didn't work for me.

**Comment by jaklan** [comment]
@anujgupta82 @argideritzalpea I have the same problem - have you found any solution? I tried all methods mentioned in pyfasttext issues and some custom tricks e.g. with CXXFLAGS and still no luck...
