### ISSUE TITLE
Error during install with python 3

### ISSUE THREAD

**Issue by streamride** [vrasneur/pyfasttext#5]
When I install via python 2, everything is ok, but with python 3 I see these errors:
cc1plus: error: unrecognized command line option "-std=c++0x"
error: command 'gcc-4.2' failed with exit status 1

How can I fix it?

**Comment by vrasneur** [comment]
Your GCC version is too old. You should try at least with GCC 4.6.

What was your compiler version when you built pyfasttext with python 2?

**Comment by streamride** [comment]
Yeah, sorry, gcc -v showed that I still using old version. Created symlink and it's ok.
