### ISSUE TITLE
Feature request/pull request: words_for_vector() --- exposes find_nearest_neighbors()

### ISSUE THREAD

**Issue by yaakov2** [vrasneur/pyfasttext#7]
The words_for_vector API exposes the functionality of the internal function self.find_nearest_neighbors: Take a vector (numpy or array.array) and return the list of k known words nearest to this vector.

https://github.com/vrasneur/pyfasttext/pull/6

**Comment by vrasneur** [comment]
Hi yaakov2,

I have merged your pull request and added some additional checks in the `words_for_vector()` method.
(See this commit: 
 https://github.com/vrasneur/pyfasttext/commit/75300cf9972137e5174208524c6c1d33a78e09c4 )

**Comment by yaakov2** [comment]
Great!
